# gen_pinned_header.ps1 — read all *.pub files in pinned/ and emit shared/PinnedKeys.h.
#
# The generated header bakes every node's Ed25519 + X25519 public key into the
# firmware build. Each node's firmware can then verify any peer's signature and
# perform key agreement without ever consulting a network service.
#
# Re-run this whenever you add a node, remove a node, or revoke a key.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$keysDir   = $PSScriptRoot
$pinnedDir = Join-Path $keysDir 'pinned'
$outPath   = Join-Path (Split-Path -Parent $keysDir) 'PinnedKeys.h'

if (-not (Test-Path $pinnedDir)) {
    throw "Pinned dir not found: $pinnedDir. Run gen_node_key.ps1 first."
}

$pubFiles = Get-ChildItem -Path $pinnedDir -Filter '*.pub' | Sort-Object Name
if ($pubFiles.Count -eq 0) {
    throw "No *.pub files in $pinnedDir. Run gen_node_key.ps1 for at least the master and one pod."
}

function Format-Bytes($bytes) {
    $hex = ($bytes | ForEach-Object { "0x{0:X2}" -f $_ }) -join ", "
    return $hex
}

function Tag-From-Filename($name) {
    # node_<name>_<id>_<algo>.pub  ->  <name>_<id>, <algo>
    if ($name -match '^node_(.+)_(ed25519|x25519)\.pub$') {
        return @{ Tag = $Matches[1]; Algo = $Matches[2] }
    }
    return $null
}

$lines = @()
$lines += "// PinnedKeys.h — AUTO-GENERATED by shared/keys/gen_pinned_header.ps1."
$lines += "// DO NOT EDIT BY HAND. Re-run the script to regenerate."
$lines += "// Generated: $(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')"
$lines += ""
$lines += "#ifndef RFTM_PINNED_KEYS_H"
$lines += "#define RFTM_PINNED_KEYS_H"
$lines += ""
$lines += "#include <stdint.h>"
$lines += ""
$lines += "namespace rftm {"
$lines += ""

# Group by tag
$tags = $pubFiles | ForEach-Object {
    $m = Tag-From-Filename $_.Name
    if ($null -ne $m) { [pscustomobject]@{ Tag=$m.Tag; Algo=$m.Algo; Path=$_.FullName } }
} | Group-Object -Property Tag | Sort-Object Name

foreach ($g in $tags) {
    $tag = $g.Name
    $cIdent = $tag -replace '[^A-Za-z0-9]', '_'
    foreach ($entry in $g.Group) {
        $bytes = [System.IO.File]::ReadAllBytes($entry.Path)
        if ($bytes.Length -ne 32) {
            throw "Pinned key $($entry.Path) is $($bytes.Length) bytes, expected 32."
        }
        $algoUpper = $entry.Algo.ToUpper()
        $varName   = "NODE_${cIdent}_${algoUpper}_PUB".ToUpper()
        $lines += "// from pinned/$(Split-Path -Leaf $entry.Path)"
        $lines += "static const uint8_t $varName[32] = {"
        $lines += "    $(Format-Bytes $bytes)"
        $lines += "};"
        $lines += ""
    }
}

$lines += "}  // namespace rftm"
$lines += ""
$lines += "#endif  // RFTM_PINNED_KEYS_H"

$lines -join "`n" | Set-Content -Path $outPath -Encoding utf8 -NoNewline

Write-Host "Wrote $outPath ($($pubFiles.Count) pubkeys)."
Write-Host "Next: run shared/sync_shared.ps1 to copy it into the sketches."
