# sync_shared.ps1 — copy shared/*.h into each Arduino sketch directory.
#
# Arduino IDE does not handle ../../shared/ includes cleanly across sketch
# boundaries on Windows. Our workaround: shared/ is the source of truth,
# and this script fans copies out to each sketch dir before compile.
# Copies are .gitignore'd; only the originals in shared/ are committed.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$repoRoot   = Split-Path -Parent $PSScriptRoot
$sharedDir  = $PSScriptRoot
$pinnedHdr  = Join-Path $repoRoot 'shared/PinnedKeys.h'

$sketches = @(
    'LoRaMeshing/SensorNode',
    'LoRaMeshing/MasterNode',
    'Rx/SoldierNode'
)

$headers = @('Protocol.h', 'LoRaConfig.h', 'AudioCues.h', 'Crypto.h')

# PinnedKeys.h is generated by gen_pinned_header.ps1; include if present.
if (Test-Path $pinnedHdr) {
    $headers += 'PinnedKeys.h'
} else {
    Write-Warning "shared/PinnedKeys.h not found. Run shared/keys/gen_pinned_header.ps1 first."
    Write-Warning "Continuing without PinnedKeys.h — sketches that require pinned keys will fail to compile."
}

foreach ($sketch in $sketches) {
    $dst = Join-Path $repoRoot $sketch
    if (-not (Test-Path $dst)) {
        Write-Warning "Sketch directory missing: $dst (skipping)"
        continue
    }
    foreach ($h in $headers) {
        $srcPath = Join-Path $sharedDir $h
        if (-not (Test-Path $srcPath)) { continue }
        $dstPath = Join-Path $dst $h
        Copy-Item -Path $srcPath -Destination $dstPath -Force
        Write-Host "  synced $h -> $sketch"
    }
}

Write-Host "Done. Open the sketches in Arduino IDE and flash."
